title: William Söderqvist # your name (or website title) here
logo: "/images/bild.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Studies Information and Communication Technology at KTH Royal Institute of Technology in Stockholm. 
  <br><br>
  Familiar with Java, C, Elixir and Prolog.
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
